# Generated by Django 4.1.1 on 2022-09-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
            ],
        ),
    ]
